# Generated by Django 4.2.1 on 2023-05-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='facebookdb',
            name='url',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
