# Generated by Django 4.2.1 on 2023-05-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_facebookdb_id_alter_facebookdb_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookdb',
            old_name='url',
            new_name='username',
        ),
    ]
